[package]
name = "sequential-id-alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = { version = "1", default-features = false }

[dev-dependencies]
proptest = { version = "1", features = ["std"] }
